const binding = require('../binding')

module.exports = {
  NCPLANE_OPTION_HORALIGNED: binding.NCPLANE_OPTION_HORALIGNED,
  NCPLANE_OPTION_VERALIGNED: binding.NCPLANE_OPTION_VERALIGNED,
  NCPLANE_OPTION_MARGINALIZED: binding.NCPLANE_OPTION_MARGINALIZED,
  NCPLANE_OPTION_FIXED: binding.NCPLANE_OPTION_FIXED,
  NCPLANE_OPTION_AUTOGROW: binding.NCPLANE_OPTION_AUTOGROW,
  NCPLANE_OPTION_VSCROLL: binding.NCPLANE_OPTION_VSCROLL,

  NCSTYLE_MASK: binding.NCSTYLE_MASK,
  NCSTYLE_ITALIC: binding.NCSTYLE_ITALIC,
  NCSTYLE_UNDERLINE: binding.NCSTYLE_UNDERLINE,
  NCSTYLE_UNDERCURL: binding.NCSTYLE_UNDERCURL,
  NCSTYLE_BOLD: binding.NCSTYLE_BOLD,
  NCSTYLE_STRUCK: binding.NCSTYLE_STRUCK,
  NCSTYLE_NONE: binding.NCSTYLE_NONE,

  NCKEY_MOD_SHIFT: binding.NCKEY_MOD_SHIFT,
  NCKEY_MOD_ALT: binding.NCKEY_MOD_ALT,
  NCKEY_MOD_CTRL: binding.NCKEY_MOD_CTRL,
  NCKEY_MOD_SUPER: binding.NCKEY_MOD_SUPER,
  NCKEY_MOD_HYPER: binding.NCKEY_MOD_HYPER,
  NCKEY_MOD_META: binding.NCKEY_MOD_META,
  NCKEY_MOD_CAPSLOCK: binding.NCKEY_MOD_CAPSLOCK,
  NCKEY_MOD_NUMLOCK: binding.NCKEY_MOD_NUMLOCK,

  NCTYPE_UNKNOWN: binding.NCTYPE_UNKNOWN,
  NCTYPE_PRESS: binding.NCTYPE_PRESS,
  NCTYPE_REPEAT: binding.NCTYPE_REPEAT,
  NCTYPE_RELEASE: binding.NCTYPE_RELEASE
}
