const binding = require('../binding')

module.exports = {
  NCPLANE_OPTION_HORALIGNED: binding.NCPLANE_OPTION_HORALIGNED,
  NCPLANE_OPTION_VERALIGNED: binding.NCPLANE_OPTION_VERALIGNED,
  NCPLANE_OPTION_MARGINALIZED: binding.NCPLANE_OPTION_MARGINALIZED,
  NCPLANE_OPTION_FIXED: binding.NCPLANE_OPTION_FIXED,
  NCPLANE_OPTION_AUTOGROW: binding.NCPLANE_OPTION_AUTOGROW,
  NCPLANE_OPTION_VSCROLL: binding.NCPLANE_OPTION_VSCROLL,

  NCSTYLE_MASK: binding.NCSTYLE_MASK,
  NCSTYLE_ITALIC: binding.NCSTYLE_ITALIC,
  NCSTYLE_UNDERLINE: binding.NCSTYLE_UNDERLINE,
  NCSTYLE_UNDERCURL: binding.NCSTYLE_UNDERCURL,
  NCSTYLE_BOLD: binding.NCSTYLE_BOLD,
  NCSTYLE_STRUCK: binding.NCSTYLE_STRUCK,
  NCSTYLE_NONE: binding.NCSTYLE_NONE,

  NCKEY_MOD_SHIFT: binding.NCKEY_MOD_SHIFT,
  NCKEY_MOD_ALT: binding.NCKEY_MOD_ALT,
  NCKEY_MOD_CTRL: binding.NCKEY_MOD_CTRL,
  NCKEY_MOD_SUPER: binding.NCKEY_MOD_SUPER,
  NCKEY_MOD_HYPER: binding.NCKEY_MOD_HYPER,
  NCKEY_MOD_META: binding.NCKEY_MOD_META,
  NCKEY_MOD_CAPSLOCK: binding.NCKEY_MOD_CAPSLOCK,
  NCKEY_MOD_NUMLOCK: binding.NCKEY_MOD_NUMLOCK,

  NCTYPE_UNKNOWN: binding.NCTYPE_UNKNOWN,
  NCTYPE_PRESS: binding.NCTYPE_PRESS,
  NCTYPE_REPEAT: binding.NCTYPE_REPEAT,
  NCTYPE_RELEASE: binding.NCTYPE_RELEASE,

  NCMICE_NO_EVENTS: binding.NCMICE_NO_EVENTS,
  NCMICE_MOVE_EVENT: binding.NCMICE_MOVE_EVENT,
  NCMICE_BUTTON_EVENT: binding.NCMICE_BUTTON_EVENT,
  NCMICE_DRAG_EVENT: binding.NCMICE_DRAG_EVENT,
  NCMICE_ALL_EVENTS: binding.NCMICE_ALL_EVENTS,

  NCBLIT_DEFAULT: binding.NCBLIT_DEFAULT,
  NCBLIT_1x1: binding.NCBLIT_1x1,
  NCBLIT_2x1: binding.NCBLIT_2x1,
  NCBLIT_2x2: binding.NCBLIT_2x2,
  NCBLIT_3x2: binding.NCBLIT_3x2,
  NCBLIT_4x2: binding.NCBLIT_4x2,
  NCBLIT_BRAILLE: binding.NCBLIT_BRAILLE,
  NCBLIT_PIXEL: binding.NCBLIT_PIXEL,
  NCBLIT_4x1: binding.NCBLIT_4x1,
  NCBLIT_8x1: binding.NCBLIT_8x1,

  NCSCALE_NONE: binding.NCSCALE_NONE,
  NCSCALE_SCALE: binding.NCSCALE_SCALE,
  NCSCALE_STRETCH: binding.NCSCALE_STRETCH,
  NCSCALE_NONE_HIRES: binding.NCSCALE_NONE_HIRES,
  NCSCALE_SCALE_HIRES: binding.NCSCALE_SCALE_HIRES,

  NCVISUAL_OPTION_NODEGRADE: binding.NCVISUAL_OPTION_NODEGRADE,
  NCVISUAL_OPTION_BLEND: binding.NCVISUAL_OPTION_BLEND,
  NCVISUAL_OPTION_HORALIGNED: binding.NCVISUAL_OPTION_HORALIGNED,
  NCVISUAL_OPTION_VERALIGNED: binding.NCVISUAL_OPTION_VERALIGNED,
  NCVISUAL_OPTION_ADDALPHA: binding.NCVISUAL_OPTION_ADDALPHA,
  NCVISUAL_OPTION_CHILDPLANE: binding.NCVISUAL_OPTION_CHILDPLANE,
  NCVISUAL_OPTION_NOINTERPOLATE: binding.NCVISUAL_OPTION_NOINTERPOLATE,

  NOTCURSES_VERSION: binding.NOTCURSES_VERSION,
  NOTCURSES_HOSTNAME: binding.NOTCURSES_HOSTNAME,
  NOTCURSES_OSVERSION: binding.NOTCURSES_OSVERSION,
  NOTCURSES_ACCOUNTNAME: binding.NOTCURSES_ACCOUNTNAME
}
